version: '3'

services:
  front:
    build: ./docker/front
    container_name: rsml_front
    volumes:
      - ./src/front:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
